// data.jsx — Mock catalog + watchlist for the Tradeit app UI kit.

const CATALOG = [
  {
    id: "charizard-ex",
    name: "Charizard ex",
    set: "Scarlet & Violet 151",
    setShort: "S&V 151",
    number: "199/197",
    rarity: "SIR",
    illustrator: "5ban Graphics",
    condition: "NM",
    productType: "single",
    price: 412.50,
    delta: 3.8,
    period: "30d",
    tendency: "Sube",
    volatility: "Media",
    variants: [
      { label: "Holo regular", price: 412.50, delta: 3.8 },
      { label: "Full Art", price: 580.00, delta: 5.1 },
      { label: "Alt Art (SIR)", price: 920.00, delta: 12.4 },
      { label: "PSA 10", price: 1740.00, delta: 18.2 },
    ],
    averages: [
      { label: "30d", value: 398.20, delta: 3.8 },
      { label: "60d", value: 376.10, delta: 9.7 },
      { label: "90d", value: 354.90, delta: 16.2 },
    ],
    listings: [
      { seller: "Camila R", condition: "NM", price: 405.00, location: "Santiago", country: "CL", verified: true },
      { seller: "Diego P",  condition: "LP", price: 380.00, location: "CDMX",     country: "MX", verified: false },
      { seller: "Mateo S",  condition: "NM", price: 410.00, location: "Buenos Aires", country: "AR", verified: true },
    ],
  },
  {
    id: "pikachu-illustrator",
    name: "Pikachu Illustrator",
    set: "Promo 1998",
    setShort: "Promo",
    number: "—",
    rarity: "Promo",
    condition: "Graded",
    productType: "graded",
    grading: "PSA 10",
    price: 5450.00,
    delta: 18.4,
    period: "90d",
    tendency: "Sube",
    volatility: "Alta",
  },
  {
    id: "sv151-etb",
    name: "Scarlet & Violet 151",
    set: "ETB sellado · EN",
    setShort: "ETB EN",
    number: "",
    rarity: "ETB",
    productType: "sealed",
    price: 78.00,
    delta: -1.2,
    period: "30d",
    tendency: "Estable",
    volatility: "Baja",
  },
  {
    id: "mewtwo-vmax",
    name: "Mewtwo VMAX",
    set: "Shining Fates",
    setShort: "S. Fates",
    number: "086/072",
    rarity: "Holo",
    condition: "LP",
    productType: "single",
    price: 145.30,
    delta: 2.1,
    period: "7d",
  },
  {
    id: "umbreon-vmax",
    name: "Umbreon VMAX",
    set: "Evolving Skies",
    setShort: "Evolv.",
    number: "215/203",
    rarity: "Alt Art",
    condition: "NM",
    productType: "single",
    price: 540.00,
    delta: 6.7,
    period: "30d",
  },
  {
    id: "rayquaza-vmax",
    name: "Rayquaza VMAX",
    set: "Evolving Skies",
    setShort: "Evolv.",
    number: "218/203",
    rarity: "Alt Art",
    condition: "NM",
    productType: "single",
    price: 285.00,
    delta: -2.3,
    period: "30d",
  },
  {
    id: "lugia-v",
    name: "Lugia V",
    set: "Silver Tempest",
    setShort: "S. Tempest",
    number: "186/195",
    rarity: "Alt Art",
    condition: "NM",
    productType: "single",
    price: 168.00,
    delta: 4.2,
    period: "30d",
  },
  {
    id: "gengar-vmax",
    name: "Gengar VMAX",
    set: "Fusion Strike",
    setShort: "Fusion",
    number: "271/264",
    rarity: "Alt Art",
    condition: "NM",
    productType: "single",
    price: 198.00,
    delta: 1.4,
    period: "30d",
  },
  {
    id: "obsidian-flames-bb",
    name: "Obsidian Flames",
    set: "Booster Box · 36p",
    setShort: "Box",
    productType: "sealed",
    price: 119.00,
    delta: 0.8,
    period: "30d",
  },
  {
    id: "espeon-v-alt",
    name: "Espeon V",
    set: "Evolving Skies",
    setShort: "Evolv.",
    number: "180/203",
    rarity: "Alt Art",
    condition: "Graded",
    productType: "graded",
    grading: "BGS 9.5",
    price: 690.00,
    delta: 7.9,
    period: "60d",
  },
];

const SETS = [
  "Todas las ediciones",
  "Scarlet & Violet 151",
  "Paldea Evolved",
  "Obsidian Flames",
  "Paradox Rift",
  "Evolving Skies",
  "Crown Zenith",
  "Silver Tempest",
];

window.CATALOG = CATALOG;
window.SETS = SETS;
